[package]
name = "chryso-parser-yacc"
version = "0.0.1"
edition = "2024"

[dependencies]
chryso-core = { version = "0.0.1", path = "../core" }
chryso-parser = { version = "0.0.1", path = "../parser" }
lrlex = "0.13"
lrpar = "0.13"

[build-dependencies]
lrlex = "0.13"
lrpar = "0.13"
