[package]
name = "chryso-optimizer"
version = "0.0.1"
edition = "2024"

[dependencies]
chryso-core = { version = "0.0.1", path = "../core" }
chryso-planner = { version = "0.0.1", path = "../planner" }
chryso-metadata = { version = "0.0.1", path = "../metadata" }
