[package]
name = "chryso-optimizer"
version = "0.1.0"
edition = "2024"

[dependencies]
chryso-core = { path = "../core" }
chryso-planner = { path = "../planner" }
chryso-metadata = { path = "../metadata" }
