[package]
name = "chryso"
version = "0.0.1"
edition = "2024"

[dependencies]
chryso-adapter = { version = "0.0.1", path = "crates/adapter", default-features = false }
chryso-core = { version = "0.0.1", path = "crates/core" }
chryso-metadata = { version = "0.0.1", path = "crates/metadata" }
chryso-optimizer = { version = "0.0.1", path = "crates/optimizer" }
chryso-parser = { version = "0.0.1", path = "crates/parser" }
chryso-planner = { version = "0.0.1", path = "crates/planner" }
ratatui = "0.29"
crossterm = "0.28"

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[workspace]
members = [
    "crates/adapter",
    "crates/core",
    "crates/metadata",
    "crates/optimizer",
    "crates/parser",
    "crates/parser_yacc",
    "crates/planner",
    "ffi",
]

[features]
default = []
duckdb = ["chryso-adapter/duckdb"]
test-utils = []


[workspace.package]
version = "0.0.1"
