[package]
name = "chryso-core"
version = "0.0.1"
edition = "2024"
description = "Chryso core crate."
license = "Apache-2.0"
repository = "https://github.com/hawkingrei/chryso"
homepage = "https://github.com/hawkingrei/chryso"
documentation = "https://docs.rs/chryso-core"

[dependencies]
