[package]
name = "chryso-planner"
version = "0.1.0"
edition = "2024"

[dependencies]
chryso-core = { path = "../core" }
chryso-metadata = { path = "../metadata" }

[dev-dependencies]
chryso-optimizer = { path = "../optimizer" }
chryso-parser = { path = "../parser" }
